server.port: 9966
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://svlada.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring:
  jackson.serialization.write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/doctorhere?currentSchema=dhsecurity
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: false
  liquibase:
    change-log: classpath:/dbchangelog/dhsecurity.db.changelog-master.xml
    drop-first: true
    contexts: sql
    enabled: true

server:
  port: 8086

oauth2.clients:
  swagger:
    clientId: swagger-user
    secret: swagger_secret
    grantType: password
    scope: swagger
  rest:
    clientid: SQMXbbFPL3
    secret: b5w-ypClrz9ED6*4s
    grantType: client_credentials
    scope: service-to-service

###############LOG - NOT: PROD ORTAMINDA ŞİFRELERİ VS YAZAR. EKLENMEZ########
logging.level.org.springframework.web: TRACE
logging.level.org.springframework.security: TRACE
logging.level.org.springframework.web.client.RestTemplate: DEBUG
logging.level.web: TRACE
logging.level.org.springframework.actuator: TRACE
logging.level.org.hibernate.SQL: TRACE
logging.level.org.hibernate.type.descriptor.sql: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE